from io import BytesIO
from typing import Any, Dict

from fastapi import APIRouter, Depends
from fastapi.responses import StreamingResponse

from app.database import audit_logs as audit_repo
from app.database import incident_events as events_repo
from app.database import investigations as investigations_repo
from app.database import recommendations as recs_repo
from app.database import response_actions as actions_repo
from app.database import security_logs as logs_repo
from app.services.auth_service import get_current_user
from app.utils.lookups import get_incident_or_404

router = APIRouter(prefix="/api/incidents", tags=["Reports"])


def build_report(incident_id: str) -> Dict[str, Any]:
    incident = get_incident_or_404(incident_id)
    links = events_repo.select(filters={"incident_id": incident["id"]})
    logs = logs_repo.select(in_={"id": [row["log_id"] for row in links]}, order="timestamp", desc=False) if links else []
    investigations = investigations_repo.select(filters={"incident_id": incident["id"]}, order="created_at", desc=True)
    recs = recs_repo.select(filters={"incident_id": incident["id"]}, order="created_at", desc=False)
    actions = actions_repo.select(filters={"incident_id": incident["id"]})
    audit = audit_repo.select(filters={"incident_id": incident["id"]}, order="timestamp", desc=False)
    return {
        "incident_id": incident.get("incident_number"),
        "internal_id": incident.get("id"),
        "date": incident.get("detected_at"),
        "severity": incident.get("severity"),
        "risk_score": incident.get("risk_score"),
        "confidence": incident.get("confidence_score"),
        "affected_user": incident.get("affected_user"),
        "affected_asset": incident.get("affected_asset"),
        "status": incident.get("status"),
        "title": incident.get("title"),
        "timeline": logs,
        "evidence": (investigations[0].get("evidence") if investigations else None) or incident.get("risk_factors"),
        "ai_assessment": investigations[0] if investigations else {"summary": incident.get("ai_summary")},
        "potential_impact": incident.get("potential_impact"),
        "recommendations": recs,
        "analyst_decision": [
            {"action_type": row.get("action_type"), "approved": row.get("approved"), "status": row.get("execution_status")}
            for row in actions
        ],
        "response": actions,
        "verification": [row.get("verification_result") for row in actions if row.get("verification_result")],
        "audit_trail": audit,
    }


@router.get("/{incident_id}/report")
def report_json_alias(incident_id: str, _: Dict[str, Any] = Depends(get_current_user)):
    return build_report(incident_id)


@router.get("/{incident_id}/report/json")
def report_json(incident_id: str, _: Dict[str, Any] = Depends(get_current_user)):
    return build_report(incident_id)


@router.get("/{incident_id}/report/pdf")
def report_pdf(incident_id: str, _: Dict[str, Any] = Depends(get_current_user)):
    from reportlab.lib.pagesizes import letter
    from reportlab.pdfgen import canvas

    report = build_report(incident_id)
    buffer = BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=letter)
    pdf.setTitle(f"CyberSentinel {report['incident_id']}")
    y = 750
    pdf.setFont("Helvetica-Bold", 16)
    pdf.drawString(40, y, f"CyberSentinel Incident Report {report['incident_id']}")
    y -= 28
    pdf.setFont("Helvetica", 10)
    lines = [
        f"Title: {report.get('title')}",
        f"Date: {report.get('date')}",
        f"Severity: {report.get('severity')}  Risk: {report.get('risk_score')}  Confidence: {report.get('confidence')}",
        f"User: {report.get('affected_user')}  Status: {report.get('status')}",
        "",
        "Timeline:",
    ]
    for log in report.get("timeline") or []:
        lines.append(f"  {log.get('timestamp')} {log.get('event_type')} {log.get('message')}")
    lines.append("")
    lines.append("This report is generated by a defensive SOC demonstration platform.")
    for line in lines:
        if y < 50:
            pdf.showPage()
            y = 750
            pdf.setFont("Helvetica", 10)
        pdf.drawString(40, y, str(line)[:110])
        y -= 14
    pdf.save()
    buffer.seek(0)
    filename = f"{report['incident_id'] or 'incident'}-report.pdf"
    return StreamingResponse(
        buffer,
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )
